### ISSUE TITLE
How to intergrate with next.js

### ISSUE THREAD

**Issue by sukechris** [Canner/slate-md-editor#59]
Thanks for your great work, it's awesome!
I want to use this editor with next.js, however, it doesn't work, here is error messages:

```js
Unexpected token .
/Users/tom/projects/demo/node_modules/rc-color-picker/assets/index.css:1
(function (exports, require, module, __filename, __dirname) { .rc-color-picker-panel-inner {
                                                              ^

SyntaxError: Unexpected token .
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/suke/projects/aza-demo/node_modules/@canner/slate-icon-fontbgcolor/lib/index.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

Any help would be appreciated!

**Comment by davidroman0O** [comment]
I have the exact same problem!

**Comment by tiotdev** [comment]
Same problem here, has anyone found a solution yet? I think some style loaders need to implemented in webpack, however, next-css and next-less don't do the trick.

**Comment by jbng** [comment]
Hi, 
Same issue.
Here are the libs I'm using:
"canner-slate-editor": "^1.5.4"
"next": "9.1.4"
"rc-color-picker": "^1.2.6"
"@zeit/next-css": "^1.0.1"

It seems that nextjs can't import a specific css source in **node_modules/slate-icon-fontbgcolor/lib/index.js**

> require("rc-color-picker/assets/index.css");
